[package]
name = "muonc_lexer"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
muonc_errors = { workspace = true }
muonc_span = { workspace = true }
muonc_middle = { workspace = true }
muonc_token = { workspace = true }

# other dependencies
