[package]
name = "muonc_middle"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
muonc_macros = { workspace = true }

# other dependencies
clap = { workspace = true }
humantime = "2.3"
thiserror = { workspace = true }
