[package]
name = "muonc_span"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
muonc_macros = { workspace = true }

# other dependencies
boxcar = { workspace = true }
bumpalo = "3.19"
dashmap = "6.1"
