[package]
name = "muonc_macros"
version.workspace = true
license.workspace = true
edition.workspace = true

[lib]

proc-macro = true

[dependencies]

# other dependencies
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
convert_case = "0.10"
